[package]
name = "rustml"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustml"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module"] }

[package.metadata.maturin]
name = "rustml"
